neuron creator

for create neuron cells in heuge nubmer for increase the efficently and decrease the time of processing

new algorithm


Model files can also be loaded from local machine
Code below needs to be run as often as files are needed. For example. if you need a .py model file and data to train on (assume it is packaged as a .zip file), you need to run the code twice to import two files:

.zip data file
.py model file
reference:

In [28]:
def upload_files():
  from google.colab import files
  uploaded = files.upload()
  for k, v in uploaded.items():
    open(k, 'wb').write(v)
  return list(uploaded.keys())

# Upload required files (pop up button will appear)
upload_files()

Saving train.py to train.py


['train.py']

In [1]:
'''
this model based on Character-Level LSTM in PyTorch form udacity
recurrent-neural-networks/char-rnn
we also use word2vec-embeddings 

objective one:
    - this aim to preidect names of items
objectice tow:
    - pridect UGI items to create user interface ( the data training from user interface was created in omflow_webApp and omflow_disktopApp)
'''

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import torch
from torch import nn
import torch.nn.functional as F
#from local library

print("i run , but i am not thinking because i am stupid roport")


i run , but i am not thinking because i am stupid roport


In [2]:
reader=pd.read_excel("trainData.xlsx","train")
reader_filter=reader[reader["category"]=="products_items"]
reader_item=reader_filter[["names","id_inside_cagegory"]]
#reader_item["id_inside_cagegory"]=reader_item[self.column2]
#https://towardsdatascience.com/multi-class-text-classification-with-lstm-1590bee1bd17
print("Info",reader_item.info())
print("reader_item",reader_item[:10])
print("reader_item[""names]",reader_item["names"][:10])

print("reader_item.id_inside_cagegory",reader_item.id_inside_cagegory[:10])

## split by new lines and spaces
#reviews_split = all_text.split('\n')
#all_text = ' '.join(reviews_split)

## create a list of words
#words = all_text.split()



<class 'pandas.core.frame.DataFrame'>
Int64Index: 1832 entries, 0 to 1881
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   names               1832 non-null   object
 1   id_inside_cagegory  1816 non-null   object
dtypes: object(2)
memory usage: 42.9+ KB
Info None
reader_item                                            names id_inside_cagegory
0                           كفر سخان فرنساوى 085                  1
1                         قاعده سخان فرنساوى 086                  2
2    كفر سخان فرنساوى 085/قاعده سخان فرنساوى 086               2sum
3        فوم تغليف علوى يمين12قدم خلفى PDFRP0075                  3
4  فوم تغليف علوى يمين امامى12قدم معدل PDFRP0123                  4
5        فوم تغليف علوى شمال12قدم خلفى PDFRP0073                  5
6       فوم تغليف علوى شمال12قدم امامى PDFRP0071                  6
7        فوم تغليف سفلى يمين12قدم معدل PDFRP0063                  7
8        فوم تغليف سفلى شما

In [3]:

reader_names=reader_item.names.value_counts()
print("______names categories________",reader_names[5])

reader_id=reader_item.id_inside_cagegory.value_counts()
print("______id categories________",reader_id)


______names categories________ 4
______id categories________ 281       11
331        9
405        8
406        8
341        8
          ..
649        1
650        1
653        1
655        1
566sum     1
Name: id_inside_cagegory, Length: 726, dtype: int64


In [4]:
#reader_inside_category=reader_item.reader_inside_category.value_counts()
# encode the text and map each character to an integer and vice versa

# we create two dictionaries:
    #first deictionaries for id
chars_id = tuple(set(reader_id))
int2char = dict(enumerate(chars_id))
char2int = {ch: ii for ii, ch in int2char.items()}

## encode the text
encoded_id = np.array([char2int[ch] for ch in reader_id])


#========================================

print("encoded_id categories",encoded_id[:100])
#data pre-process for names



encoded_id categories [9 8 7 7 7 7 6 6 6 6 6 6 6 6 6 6 6 6 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


In [5]:
chars_names = tuple(set(reader_names))
int2char_id = dict(enumerate(chars_id))
char2int_id = {ch: ii for ii, ch in int2char.items()}
print("____________ reader_name categories",reader_names[5])
## encode the text
encoded_names= np.array([char2int[ch] for ch in reader_names])
print("encoded_name categories",encoded_names[:100])




____________ reader_name categories 4
encoded_name categories [3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [6]:

    #second deictionaries for name
#filter names by id
#list_id=list(reader_item["id_inside_cagegory"])
print("reader_id",reader_names.value_counts())
names=[]
for id in reader_id.value_counts():
    reader_item_filter=reader_item[reader_item["id_inside_cagegory"]==id]
    names_items=[]
    for i in reader_item_filter.names:
        names_items.append(reader_item_filter.names)
        names.append(names_items)
    #return names
print("names",names[:5])
writer = pd.ExcelWriter("defined_name.xlsx")
names_df=pd.DataFrame(names)
names_df.to_excel(writer,"data")
writer.save()


reader_id 1    697
2    392
3    105
4      9
Name: names, dtype: int64
names [[343     شتلات دلتا سمارت-8عين
1024         شتلات دلتا سمارت
1818             شتلات سمارت 
Name: names, dtype: object, 343     شتلات دلتا سمارت-8عين
1024         شتلات دلتا سمارت
1818             شتلات سمارت 
Name: names, dtype: object, 343     شتلات دلتا سمارت-8عين
1024         شتلات دلتا سمارت
1818             شتلات سمارت 
Name: names, dtype: object], [343     شتلات دلتا سمارت-8عين
1024         شتلات دلتا سمارت
1818             شتلات سمارت 
Name: names, dtype: object, 343     شتلات دلتا سمارت-8عين
1024         شتلات دلتا سمارت
1818             شتلات سمارت 
Name: names, dtype: object, 343     شتلات دلتا سمارت-8عين
1024         شتلات دلتا سمارت
1818             شتلات سمارت 
Name: names, dtype: object], [343     شتلات دلتا سمارت-8عين
1024         شتلات دلتا سمارت
1818             شتلات سمارت 
Name: names, dtype: object, 343     شتلات دلتا سمارت-8عين
1024         شتلات دلتا سمارت
1818             شتلات سمارت 


In [7]:
import utiliy
from utiliy import one_hot_encode,get_batches

test_seq = np.array([[3, 5, 1]])
one_hot = one_hot_encode(test_seq, 8)

print("____one_hot____",one_hot)

batches = get_batches(encoded_id, 8, 50)
print("batches",batches)
x, y = next(batches)
# printing out the first 10 items in a sequence
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])


____one_hot____ [[[0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]]]
batches <generator object get_batches at 0x7efba56a97d0>
x
 [[9 8 7 7 7 7 6 6 6 6]
 [4 4 4 4 4 4 4 4 4 4]
 [3 3 3 3 3 3 3 3 3 3]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]

y
 [[8 7 7 7 7 6 6 6 6 6]
 [4 4 4 4 4 4 4 4 4 4]
 [3 3 3 3 3 3 3 3 3 3]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [8]:


batches_name = get_batches(encoded_names, 8, 50)
z, t = next(batches_name)
# printing out the first 10 items in a sequence
print('z\n', z[:10, :10])
print('\ny\n', t[:10, :10])
# check if GPU is available
train_on_gpu = torch.cuda.is_available()
if(train_on_gpu):
    print('Training on GPU!')
else: 
    print('No GPU available, training on CPU; consider making n_epochs very small.')



z
 [[3 3 3 3 3 3 3 3 3 2]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

y
 [[3 3 3 3 3 3 3 3 2 2]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
No GPU available, training on CPU; consider making n_epochs very small.


In [9]:

from network import TextRnn as Model
## : set you model hyperparameters
# define and print the net
n_hidden=512
n_layers=2

#net = Model(chars_names, n_hidden, n_layers)
#device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

#net = Model(chars_id, n_hidden, n_layers).to(device)
net = Model(chars_id, n_hidden, n_layers)
#optimizer = optim.Adam(model.parameters())
#loss_fn = torch.nn.BCELoss()

print(net)





TextRnn(
  (lstm): LSTM(10, 512, num_layers=2, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.5, inplace=False)
  (fc): Linear(in_features=512, out_features=10, bias=True)
)


start to train

In [10]:
import train
from train import TexTrainer

batch_size = 128
seq_length = 100
n_epochs =  20 # start small if you are just testing initial behavior

# train the model
TexTrainer.train(net, encoded_id, n_epochs, batch_size, seq_length, lr=0.001, print_every=10)

the login the file train successfuly
data [9 8 7 7 7 7 6 6 6 6 6 6 6 6 6 6 6 6 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
batch_size 128
seq_length 100
epochs 20
get batches <generator object get_batches at 0x7efba567d450>
init_hiding for batch (tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]]), tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  

In [11]:
## change the name, for saving multiple files

model_name = 'rnn_x_epoch.net'

checkpoint = {'n_hidden': net.n_hidden,
            'n_layers': net.n_layers,
            'state_dict': net.state_dict(),
            'tokens': net.chars}

with open(model_name, 'wb') as f:
    torch.save(checkpoint, f)
# change the name, for saving multiple files

model_name = 'rnn_x_epoch.net'

checkpoint = {'n_hidden': net.n_hidden,
            'n_layers': net.n_layers,
            'state_dict': net.state_dict(),
            'tokens': net.chars}

with open(model_name, 'wb') as f:
    torch.save(checkpoint, f)